name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta todos los días a medianoche
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Generar animación del snake
        uses: Platane/snk@v3
        with:
          github_user_name: CALR0
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Subir archivo a la rama output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
