name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Ejecuta todos los días a medianoche
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Generar animación del snake
        uses: Platane/snk@v3
        with:
          github_user_name: CALR0
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Commit y push del archivo generado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "🐍 Generate snake animation"
          add: "output/github-contribution-grid-snake.svg"
